name: Terraform Plan

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  terraform:
    name: Terraform Plan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.5.0"

    - name: Terraform Init
      run: |
        cd live
        terraform init

    - name: Terraform Format
      run: |
        cd live
        terraform fmt -check

    - name: Terraform Validate
      run: |
        cd live
        terraform validate

    - name: Terraform Plan
      run: |
        cd live
        terraform plan -var-file=../envs/dev.tfvars -no-color
      continue-on-error: true